.PHONY: build install test clean try try-stop screenshot demo demo-gif release auto patch minor major hooks web web-dev web-test

build:
	cargo build --release

# The page `tenx web` serves: web/ is a Next.js static export (web/out) that
# build.rs embeds in the binary; without it the binary serves a stub that
# says to run this. Needs Node 22+ and pnpm (corepack enable). Touching
# build.rs makes cargo notice the export on the next build.
web:
	cd web && pnpm install --frozen-lockfile && pnpm build
	touch build.rs

# The page with hot reload against a running `tenx web --dev-origin
# http://localhost:3000` (its token in NEXT_PUBLIC_TENX_TOKEN, or ?token= on
# the page's URL).
web-dev:
	cd web && pnpm install --frozen-lockfile && NEXT_PUBLIC_TENX_URL=$${NEXT_PUBLIC_TENX_URL:-http://127.0.0.1:7070} pnpm dev

# The page's smoke test: the built export against web/tests/mock-server.mjs,
# in a headless browser. Not part of `make test` — it needs Node and a
# Playwright browser (`pnpm exec playwright install chromium`).
web-test: web
	cd web && pnpm lint && pnpm test:smoke

# Point git at the versioned hooks (.githooks/): commit-msg rejects messages
# that are not Conventional Commits, since they become the changelog and
# decide the version bump. Once per clone; worktrees of it inherit the setting.
hooks:
	git config core.hooksPath .githooks
	@echo "  ✓ hooks enabled (core.hooksPath = .githooks)"

# Try this build without installing it: its own tmux server (`-L try`), its
# own generated config and watcher, the same workspaces and tasks. An
# installed tenx is unaffected.
try: build
	TENX_TMUX_SOCKET=try ./target/release/tenx

try-stop:
	-tmux -L try kill-server

# Installs the binary to ~/.cargo/bin (cargo's default, same as `cargo install`).
# Nothing else to place: the tmux config is generated at `~/.config/tenx/tmux.conf`
# whenever the tenx session is created, and it embeds this binary's path.
#
# A running tenx server keeps the config it started with (tmux reads it once,
# at server start). After an install that changes the generated config, restart
# the session to pick it up: `tmux -L tenx kill-server`, then `tenx`.
install:
	cargo install --path .
	@echo "  ✓ installed — run 'tenx' to (re)create the session"

test:
	cargo test -p tenx-cli -p tenx-core
	cargo clippy -p tenx-cli -p tenx-core --all-targets -- -D warnings

# Regenerate docs/column.svg from the column's own widgets and fixture data
# (src/tui/column/screenshot.rs) — no real workspace involved.
screenshot:
	TENX_SCREENSHOT=1 cargo test -p tenx-cli --bin tenx screenshot -- --nocapture

# Cut a release: `make release auto|patch|minor|major`. The version is never
# typed: `auto` derives it from the commits since the last tag (git-cliff,
# cliff.toml), the others bump that part of Cargo.toml's version. Bumps both
# crates, generates the CHANGELOG section, commits `release vX.Y.Z`, pushes main
# and dispatches .github/workflows/release.yml (generated by cargo-dist),
# which builds the binaries, publishes the GitHub Release and the Homebrew
# formula, and creates the tag. The same thing runs from the Actions tab via
# bump.yml. `make release minor DRY=1` only prints the version it would cut.
BUMP := $(filter auto patch minor major,$(MAKECMDGOALS))
auto patch minor major:
	@:
release:
	@test -n "$(BUMP)" || { echo "usage: make release auto|patch|minor|major [DRY=1]"; exit 1; }
	./scripts/release.sh $(BUMP) $(if $(DRY),--dry-run,--push)

# Regenerate docs/demo.svg (animated) and docs/demo.cast (asciinema) by
# playing a scripted client session — the column beside a fixture task —
# (src/tui/column/demo.rs). Nothing is recorded; every frame is rendered.
demo:
	TENX_DEMO=1 cargo test -p tenx-cli --bin tenx demo -- --nocapture

# Render docs/demo.gif from the cast with agg (`brew install agg`;
# bump.yml downloads a pinned binary). Text in JetBrains Mono, falling back
# to whatever monospace the machine has; the theme is the palette's ground.
# scripts/release.sh runs `demo demo-gif` so a release ships a current demo.
demo-gif:
	agg --text-font-family "JetBrains Mono,Menlo,DejaVu Sans Mono" --emoji-font-family "Noto Color Emoji,Apple Color Emoji" --font-size 14 --last-frame-duration 3 --theme "171820,d6dbe3,171820,e5707b,7ac27c,e4a854,6896dc,a78bfa,6896dc,d6dbe3" docs/demo.cast docs/demo.gif

clean:
	cargo clean
