.PHONY: build install test clean try try-stop screenshot demo demo-gif release auto patch minor major hooks

build:
	cargo build --release

# Point git at the versioned hooks (.githooks/): commit-msg rejects messages
# that are not Conventional Commits, since they become the changelog and
# decide the version bump. Once per clone; worktrees of it inherit the setting.
hooks:
	git config core.hooksPath .githooks
	@echo "  ✓ hooks enabled (core.hooksPath = .githooks)"

# Try this build without installing it: its own tmux server (`-L try`), its
# own generated config and watcher, the same workspaces and tasks. Ctrl+w and
# the home overlay run this build too. An installed tenx is unaffected.
try: build
	TENX_TMUX_SOCKET=try ./target/release/tenx

try-stop:
	-tmux -L try kill-server

# Installs the binary to ~/.cargo/bin (cargo's default, same as `cargo install`).
# Nothing else to place: the tmux config is generated at `~/.config/tenx/tmux.conf`
# whenever the tenx session is created, and it embeds this binary's path.
#
# A running tenx server keeps the config it started with (tmux reads it once,
# at server start). After an install that changes the generated config, restart
# the session to pick it up: `tmux -L tenx kill-server`, then `tenx`.
install:
	cargo install --path .
	@echo "  ✓ installed — run 'tenx' to (re)create the session"

test:
	cargo test -p tenx-cli -p tenx-core
	cargo clippy -p tenx-cli -p tenx-core --all-targets -- -D warnings

# Regenerate docs/overlay.svg from the overlay's own widgets and fixture
# data (src/tui/overlay/screenshot.rs) — no real workspace involved.
screenshot:
	TENX_SCREENSHOT=1 cargo test -p tenx-cli --bin tenx screenshot -- --nocapture

# Cut a release: `make release auto|patch|minor|major`. The version is never
# typed: `auto` derives it from the commits since the last tag (git-cliff,
# cliff.toml), the others bump that part of Cargo.toml's version. Bumps both
# crates, generates the CHANGELOG section, commits `release vX.Y.Z`, pushes main
# and dispatches .github/workflows/release.yml (generated by cargo-dist),
# which builds the binaries, publishes the GitHub Release and the Homebrew
# formula, and creates the tag. The same thing runs from the Actions tab via
# bump.yml. `make release minor DRY=1` only prints the version it would cut.
BUMP := $(filter auto patch minor major,$(MAKECMDGOALS))
auto patch minor major:
	@:
release:
	@test -n "$(BUMP)" || { echo "usage: make release auto|patch|minor|major [DRY=1]"; exit 1; }
	./scripts/release.sh $(BUMP) $(if $(DRY),--dry-run,--push)

# Regenerate docs/overlay-demo.svg (animated) and docs/overlay-demo.cast
# (asciinema) by playing a scripted scene against the fixture overlay
# (src/tui/overlay/demo.rs). Nothing is recorded; every frame is rendered.
demo:
	TENX_DEMO=1 cargo test -p tenx-cli --bin tenx demo -- --nocapture

# Render docs/overlay-demo.gif from the cast with agg (`brew install agg`;
# bump.yml downloads a pinned binary). Text in JetBrains Mono, falling back
# to whatever monospace the machine has; the theme is the palette's ground.
# scripts/release.sh runs `demo demo-gif` so a release ships a current demo.
demo-gif:
	agg --text-font-family "JetBrains Mono,Menlo,DejaVu Sans Mono" --emoji-font-family "Noto Color Emoji,Apple Color Emoji" --font-size 14 --last-frame-duration 3 --theme "171820,d6dbe3,171820,e5707b,7ac27c,e4a854,6896dc,a78bfa,6896dc,d6dbe3" docs/overlay-demo.cast docs/overlay-demo.gif

clean:
	cargo clean
