// Generates src/palette.css and src/palette.ts from src/palette.rs, the one
// palette the column TUI and the tmux theme are painted with, so the page
// can't drift from them. Runs before `dev` and `build`; the outputs are
// committed so a checkout type-checks without running it.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, '../../src/palette.rs'), 'utf8');

const num = (s) => (s.startsWith('0x') ? parseInt(s, 16) : parseInt(s, 10));
const hex = (r, g, b) => '#' + [r, g, b].map((n) => num(n).toString(16).padStart(2, '0')).join('');

// `pub const NAME: Rgb = Rgb(r, g, b);`
const roles = {};
for (const m of src.matchAll(/pub const (\w+): Rgb = Rgb\(\s*([\dxa-fA-F]+),\s*([\dxa-fA-F]+),\s*([\dxa-fA-F]+)\s*\)/g)) {
  roles[m[1]] = hex(m[2], m[3], m[4]);
}
// `pub const WORKSPACE: [Rgb; N] = [ Rgb(..), ... ];` — kept for completeness;
// the server sends each workspace's colour already picked.
const ws = src.match(/pub const WORKSPACE: \[Rgb; \d+\] = \[([\s\S]*?)\];/);
const workspace = ws ? [...ws[1].matchAll(/Rgb\(\s*(\w+),\s*(\w+),\s*(\w+)\s*\)/g)].map((m) => hex(m[1], m[2], m[3])) : [];

const required = ['ACCENT', 'MUTED', 'TEXT', 'SEL_BG', 'SEL_TEXT', 'IDLE', 'BORDER', 'BORDER_ACTIVE', 'CHIP_INPUT_BG', 'CHIP_SECRETS_BG', 'CURRENT', 'BRIGHT', 'DANGER', 'SUCCESS', 'WARN', 'INFO', 'GROUND'];
const missing = required.filter((r) => !roles[r]);
if (missing.length) {
  console.error(`palette.mjs: src/palette.rs lacks ${missing.join(', ')}`);
  process.exit(1);
}

const kebab = (s) => s.toLowerCase().replace(/_/g, '-');
const header = '/* Generated by web/scripts/palette.mjs from src/palette.rs — do not edit. */\n';
const css = header + ':root {\n' + Object.entries(roles).map(([k, v]) => `  --${kebab(k)}: ${v};`).join('\n') + '\n}\n';
const ts =
  header.replace('/*', '//').replace(' */', '') +
  `export const palette = ${JSON.stringify(roles, null, 2)} as const;\n\n` +
  `export const workspaceColors = ${JSON.stringify(workspace)} as const;\n`;

writeFileSync(join(here, '../src/palette.css'), css);
writeFileSync(join(here, '../src/palette.ts'), ts);
