// Generated by web/scripts/palette.mjs from src/palette.rs — do not edit.
export const palette = {
  "ACCENT": "#a78bfa",
  "MUTED": "#787f8c",
  "TEXT": "#d6dbe3",
  "SEL_BG": "#212734",
  "SEL_TEXT": "#eceff5",
  "IDLE": "#606878",
  "BORDER": "#343a46",
  "BORDER_ACTIVE": "#606878",
  "CHIP_INPUT_BG": "#3a2e18",
  "CHIP_SECRETS_BG": "#2a2440",
  "CURRENT": "#78a0e6",
  "BRIGHT": "#e2e6ee",
  "DANGER": "#e5707b",
  "SUCCESS": "#7ac27c",
  "WARN": "#e4a854",
  "INFO": "#6896dc",
  "GROUND": "#171820"
} as const;

export const workspaceColors = ["#5eb4aa","#ce86a8","#aab064","#c4a882","#78b4ce","#ba92ce","#d68e74","#8cb08a"] as const;
